spring.application.name=springMagisterka

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:8090/spring_magisterka
spring.datasource.username=postgres
spring.datasource.password=TjtPO93RGHcX4KPTtf8kjyu9kYnjOtAG
spring.datasource.driver-class-name=org.postgresql.Driver


# --- MongoDB ---
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=magisterka_database

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
