spring.application.name=springMagisterka
# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:8090/spring_magisterka
spring.datasource.username=postgres
spring.datasource.password=YvPgF0RQa3TsOuFC6KuGN--J-ydLTRwb
spring.datasource.driver-class-name=org.postgresql.Driver

# --- MongoDB ---
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=magisterka_database

#automatic actualization postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect